Vagrant.configure("2") do |config|
  config.vm.box = "fscm/postgresql"
  config.vm.box_version = "9.6.1"
  config.vm.network "forwarded_port", guest: 5432, host: 5432, host_ip: "127.0.0.1"
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end
end